export const m_ProjectData = [
    {
        id: 1,
        title: "Axis:Save",
        description: "<strong>■ 設計方針</strong>\n演出とゲームロジックの責務分離を重視。\nPlayerControllerは入力・物理のみを担当し、演出処理はCinematicManagerへ集約。\n演出中は m_IsEventLocked により外部から状態制御を行う構造とした。\n\n<strong>■ 物理干渉問題への対応</strong>\n演出中に移動・衝突が破綻する問題が発生。\n以下で解決：\n\n▸ FixedUpdate内での早期return\n▸ Physics.IgnoreLayerCollisionによる当たり判定停止\n▸ UniTaskによるフレーム同期制御\n\n<strong>■ カメラ演出設計</strong>\n▸ Lens.FieldOfViewを直接制御\n▸ elapsed / animationLength による補間係数算出\n▸ Mathf.Lerpで時間的緩急を設計\n▸ CinemachineBlendを動的にCutへ変更\n\n<strong>制作期間</strong> : 3ヶ月 &emsp; <strong>チーム人数</strong> : 個人制作 &emsp; <strong>プラットフォーム</strong> : PC / Windows",
        descriptionEn: "<strong>■ Design Policy</strong>\nEmphasized the separation of responsibilities between presentation and game logic.\nPlayerController handles only input and physics, while presentation processing is consolidated in CinematicManager.\nStructured to control state externally using m_IsEventLocked during events.\n\n<strong>■ Resolution of Physics Interference Issues</strong>\nAddressed issues where movement and collisions broke down during events.\nSolved by:\n\n▸ Early return in FixedUpdate\n▸ Suspending collision detection using Physics.IgnoreLayerCollision\n▸ Frame synchronization control using UniTask\n\n<strong>■ Camera Presentation Design</strong>\n▸ Direct control of Lens.FieldOfView\n▸ Calculation of interpolation coefficient using elapsed / animationLength\n▸ Designing temporal easing with Mathf.Lerp\n▸ Dynamically changing CinemachineBlend to Cut\n\n<strong>Duration</strong> : 3 months &emsp; <strong>Team</strong> : Solo &emsp; <strong>Platform</strong> : PC / Windows",
        videoUrl: "/projects/AxisSave/Game4.mp4",
        imageUrls: [
            "/projects/AxisSave/AxisSave1.png",
            "/projects/AxisSave/AxisSave2.png",
            "/projects/AxisSave/AxisSave3.png",
            "/projects/AxisSave/AxisSave4.png",
        ],
        githubUrl: "https://github.com/chogeru/3DCombat",
        downloadUrl: "https://drive.google.com/drive/folders/1mN7YWpIgN0pv2fasbTTO-C3A3vCtW4GQ?usp=drive_link",
        backgroundUrl: "/projects/AxisSave/AxisSaveBack.png",
        technologies: ["Unity", "C#", "HLSL"],
    },
    {
        id: 2,
        title: "PlanetariumVR",
        description: "<strong>■ 技術テーマ</strong>\nVR空間における視線連動型プレゼンテーション制御の実装\n\n<strong>■ 実装内容</strong>\n<strong>① 視線連動型3Dオーディオ制御</strong>\n▸ <code>Vector3.Dot</code> による視線方向と対象方向の内積計算\n▸ 視線一致度に応じた音量変化制御\n▸ <code>Mathf.Lerp</code> による滑らかな補間処理\n▸ <code>AudioSource.spatialBlend = 1.0f</code> による3D音響化\n→ プレイヤーが対象を向くほど音声が強調される空間的演出を実現\n\n<strong>② 非同期プレゼン進行管理</strong>\n▸ <code>UniTask.WaitWhile()</code> による音声再生終了待機\n▸ イベント駆動型の進行制御設計\n▸ <code>UniTask.Yield()</code> を用いたフレーム同期型フェード処理\n→ 音声終了をトリガーとした自然なスライド進行を実装\n\n<strong>③ フェード演出システム</strong>\n▸ <code>Coroutine</code> による段階的フェード処理\n▸ <code>Time.time</code> ベースの補間制御\n▸ <code>Image / SpriteRenderer</code> のアルファ操作\n→ VR空間における視覚的没入感を向上\n\n<strong>④ ビルボードUI設計</strong>\n▸ <code>Quaternion.LookRotation</code> によるY軸回転制御\n▸ 常時プレイヤー正面維持UI設計\n→ VR空間内で視認性を損なわない情報提示を実現\n\n<strong>■ 技術的特徴</strong>\n非同期処理とコルーチンの併用設計\nイベント駆動型進行管理\nベクトル演算を用いた空間認識制御\nVRUXを意識した音響・UI統合設計\n\n<strong>■ 成果・得られた価値</strong>\n<strong>UX向上</strong>\n<code>Vector3.Dot</code> による視線ベクトルと対象オブジェクト方向ベクトルの内積計算を用いて、視線方向と音量・UI演出をリアルタイム連動。これにより、VR空間特有の視線誘導の難しさを解消し、ユーザー操作を必要としない自然な情報提示フローを実現。没入感と直感性を両立したプレゼンテーション体験を構築した。\n\n<strong>保守性・拡張性の向上</strong>\n<code>UniTask</code> による非同期制御（音声再生終了待機・イベント駆動進行管理）を導入し、従来のフラグ依存型制御を排除。状態遷移を明示的なシーケンス管理へ再構築することで、スライドや音声素材の追加・差し替えに対する影響範囲を限定。拡張容易性と可読性を両立したアーキテクチャを確立した。\n\n<strong>制作期間</strong> : 3日 &emsp; <strong>チーム人数</strong> : 個人制作 &emsp; <strong>プラットフォーム</strong> : VR",
        descriptionEn: "<strong>■ Technical Theme</strong>\nImplementation of gaze-linked presentation control in VR space\n\n<strong>■ Implementation Details</strong>\n<strong>① Gaze-Linked 3D Audio Control</strong>\n▸ Target direction calculation via <code>Vector3.Dot</code>\n▸ Volume control based on gaze alignment degree\n▸ Smooth interpolation using <code>Mathf.Lerp</code>\n▸ 3D spatialization with <code>AudioSource.spatialBlend = 1.0f</code>\n→ Spatial presentation where audio is emphasized as the player faces the target\n\n<strong>② Asynchronous Presentation Management</strong>\n▸ Waiting for audio completion with <code>UniTask.WaitWhile()</code>\n▸ Event-driven progression control design\n▸ Frame-synced fade processing using <code>UniTask.Yield()</code>\n→ Natural slide progression triggered by audio completion\n\n<strong>③ Fade Presentation System</strong>\n▸ Step-by-step fade processing via <code>Coroutine</code>\n▸ Interpolation control based on <code>Time.time</code>\n▸ Alpha manipulation of <code>Image / SpriteRenderer</code>\n→ Enhanced visual immersion in VR space\n\n<strong>④ Billboard UI Design</strong>\n▸ Y-axis rotation control using <code>Quaternion.LookRotation</code>\n▸ UI designed to constantly face the player\n→ Information presentation that doesn't compromise visibility in VR\n\n<strong>■ Technical Features</strong>\nCombined asynchronous tasks & coroutines\nEvent-driven progression management\nSpatial recognition control using vector math\nAudio & UI integration focused on VR UX\n\n<strong>■ Outcomes & Value Gained</strong>\n<strong>UX Improvement</strong>\nUtilized dot product calculation of gaze and target object vectors via <code>Vector3.Dot</code> to link gaze direction with volume and UI presentation in real time. This resolves the difficulty of guiding gaze in VR spaces, realizing a natural information flow without requiring user operation, building an immersive and intuitive presentation experience.\n\n<strong>Enhanced Maintainability & Scalability</strong>\nIntroduced async control using <code>UniTask</code> (waiting for audio completion, event-driven progression management), eliminating traditional flag-dependent control. By reconstructing state transitions into explicit sequence management, the scope of impact when adding or replacing slides and audio assets is minimized, establishing an architecture that balances extensibility and readability.\n\n<strong>Duration</strong> : 3 days &emsp; <strong>Team</strong> : Solo &emsp; <strong>Platform</strong> : VR",
        videoUrl: "",
        imageUrls: [
            "/projects/PlanetariumVR/PlanetariumVR1.png",
            "/projects/PlanetariumVR/Planetarium2.png",
        ],
        githubUrl: "https://github.com/sogotoya/Planetarium_VR",
        downloadUrl: "https://drive.google.com/drive/folders/1gKum3c_dI211KniKmo8cWO2rhy93Dcph?usp=sharing",
        backgroundUrl: "/projects/PlanetariumVR/PlanetariumVRBack.png",
        technologies: ["Unity", "C#", "VR"],
    },
    {
        id: 3,
        title: "DartsVR",
        description: "VRダーツゲーム制作中",
        descriptionEn: "A VR darts game (in production)",
        videoUrl: "",
        imageUrls: [
            "/projects/DartsVR/DartsVR1.png",
            "/projects/DartsVR/DartsVR2.png",
        ],
        githubUrl: "",
        downloadUrl: "",
        backgroundUrl: "/projects/DartsVR/DartsVRBack.png",
        technologies: ["Unity", "C#", "VR"],
    },
    {
        id: 4,
        title: "Orimichikun",
        description: "<strong>■ 技術テーマ</strong>\n拡張性と実行効率を両立させたState Machineベース戦闘AIの設計と最適化\n\n<strong>■ 現在の設計（実装済み）</strong>\n<strong>State Pattern によるボスAI制御</strong>\n各攻撃（Move / Roll / Hari など）を個別ステートクラスとして分離し、状態遷移を明確化。\n\n<strong>Time.deltaTime を用いたフレームレート非依存移動</strong>\ntransform加算による安定した速度制御を実装。\n\n<strong>攻撃ロジックの責務分離</strong>\n巨大な単一クラスを避け、攻撃単位でクラス分割することで可読性を向上。\n\n<strong>■ 現在の課題</strong>\n▸ パラメータがコード依存（データ駆動未達）\n▸ Instantiate依存によるGC発生リスク\n▸ Coroutine主体の非同期制御\n▸ transform直操作による物理拡張制限\n\n<strong>■ 改善方針</strong>\n▸ ScriptableObject化によるパラメータ外部化\n▸ ObjectPool導入によるメモリ負荷軽減\n▸ 非同期制御の整理（UniTask導入検討）\n▸ 物理設計思想の明文化または再設計\n\n<strong>制作期間</strong> : 3週間 &emsp; <strong>チーム人数</strong> : 2人 &emsp; <strong>プラットフォーム</strong> : PC / スマホ",
        descriptionEn: "<strong>■ Technical Theme</strong>\nDesign and optimization of a State Machine-based combat AI balancing extensibility and execution efficiency.\n\n<strong>■ Current Design (Implemented)</strong>\n<strong>Boss AI Control via State Pattern</strong>\nSeparated each attack (Move / Roll / Hari, etc.) into individual state classes, clarifying state transitions.\n\n<strong>Framerate-Independent Movement via Time.deltaTime</strong>\nImplemented stable speed control using transform addition.\n\n<strong>Separation of Attack Logic Responsibilities</strong>\nImproved readability by avoiding massive single classes and dividing classes per attack unit.\n\n<strong>■ Current Issues</strong>\n▸ Parameters are hard-coded (Data-driven approach not yet achieved)\n▸ GC occurrence risk due to Instantiate dependency\n▸ Asynchronous control primarily relies on Coroutines\n▸ Physics extension limitations due to direct transform manipulation\n\n<strong>■ Improvement Policy</strong>\n▸ Externalize parameters via ScriptableObjects\n▸ Reduce memory load by introducing ObjectPool\n▸ Reorganize asynchronous control (Considering UniTask integration)\n▸ Clarify or redesign physics design philosophy\n\n<strong>Duration</strong> : 3 weeks &emsp; <strong>Team</strong> : 2 people &emsp; <strong>Platform</strong> : PC / Mobile",
        videoUrl: "",
        imageUrls: [
            "/projects/Orimichikun/Orimichikun2.png",
            "/projects/Orimichikun/Orimichikun3.png",
            "/projects/Orimichikun/Orimichikun4.png",
            "/projects/Orimichikun/Orimichikun5.png",
            "/projects/Orimichikun/Orimichikun1.png",
        ],
        githubUrl: "https://github.com/sogotoya/Orimichikun",
        downloadUrl: "https://drive.google.com/file/d/17AjwSIBC5E0qQm1ME8txIx4mbA7m5UvG/view?usp=drive_link",
        backgroundUrl: "/projects/Orimichikun/OrimichikunBack.png",
        technologies: ["Unity", "C#"],
    },
];

// ツール一覧
export const m_ToolData = [
    {
        id: "tool-1",
        title: "BatchProcessAutomation",
        description: "このツールは、プロジェクトの健康診断（エラーチェック）や各種の自動処理を、複数まとめて一気に実行できる便利な機能です。\nビルド前（ゲームを書き出す前）の最終チェックなどに活用できます。",
        descriptionEn: "Unity Editor Extension",
        imageUrls: [
            "/projects/Tools/BatchProcessAutomation/BatchProcessAutomation1.png",
            "/projects/Tools/BatchProcessAutomation/BatchProcessAutomation2.png",
            "/projects/Tools/BatchProcessAutomation/BatchProcessAutomation3.png",
        ],
        backgroundUrl: "/projects/Tools/BatchProcessAutomation/BatchProcessAutomation1.png",
        technologies: ["Unity", "C#"],
        githubUrl: "#",
        downloadUrl: "https://drive.google.com/drive/folders/1Bs2oXTUNJAlu1QVL9lsFN-VkI8JHCImW?usp=sharing",
    },
    {
        id: "tool-2",
        title: "AssetDependencyVisualizer",
        description: "プロジェクト内の「アセット同士のつながり」を可視化するEditor拡張ツールです。\nテクスチャ・プレハブ・マテリアルなどの使用状況を簡単に確認でき、\nどこからも参照されていない不要なアセットの特定に役立ちます。",
        descriptionEn: "Unity Editor Extension",
        imageUrls: [
            "/projects/Tools/AssetDependencyVisualizer/AssetDependencyVisualizer1.png",
            "/projects/Tools/AssetDependencyVisualizer/AssetDependencyVisualizer2.png",
            "/projects/Tools/AssetDependencyVisualizer/AssetDependencyVisualizer3.png",
        ],
        backgroundUrl: "/projects/Tools/AssetDependencyVisualizer/AssetDependencyVisualizer1.png",
        technologies: ["Unity", "C#"],
        githubUrl: "#",
        downloadUrl: "https://drive.google.com/drive/folders/1WGPgiF_Zeddhv4zD2E1y0kbZG9-2qNsW?usp=sharing",
    },
];

// ゲームジャム作品
export const m_GameJamData = [
    {
        id: "gj-1",
        title: "Global",
        description: "開発人数：2名（双方途中参加）\n制作期間：36時間\n担当：ゲームシーン設計・実装全般（Unity / C#）\n\n【概要】\n短期間かつ途中参加という制約下で、ゲームシーンの設計整理から実装までを担当。既存構造を把握した上で、仕様の再定義とロジックの再構築を行い、最終的に動作する形まで完成させた。\n\n【アーキテクチャ設計】\nNPC生成・個体制御・ランダムイベント管理をクラス単位で責務分離。\n\n・ScreenEdgeSpawner：NPCスポーン管理および確率制御\n・PersonController：個体の移動・状態管理\n・RandomEventManager：天候などの外部イベント制御\n\n生成管理と個体挙動を分離することで、スポーン仕様変更やイベント追加に耐えられる構造を構築した。\n\n【NPC経路制御設計】\n3種類の経路パターン（通過型／密集地点向かい型／特定地点誘導型）を実装。\nスポーン時に確率ベースでルートを割り当て、個体側で挙動を分岐制御。\n役割ごとに状態を持たせることで処理の肥大化を防いだ。\n\n【外部イベントによる状態割り込み】\n雨イベント発生時に、既存状態を上書きする処理を実装。\n状態競合を防ぐ条件分岐を設け、二重実行を回避。アニメーション同期を維持したまま安全にステートを切り替える構造を設計した。\n\n【エディタ拡張による効率化】\nCharacterCreatorEditor（Unity Editor拡張）を実装。\nキャラクター生成およびアニメーション設定の自動化を行い、手作業工程を削減。短期開発における設定コストを抑制した。\n\n【設計判断】\n開発期間から逆算し、体験の中核に直結しない要素は段階実装へ変更。\nロジックの安定性を優先し、拡張要素よりも状態管理の完成度を重視した。",
        descriptionEn: "Team Size: 2 (both joined mid-development)\nDevelopment Time: 36 hours\nRole: Game scene design & full implementation (Unity / C#)\n\n[Overview]\nUnder the constraints of a short 36-hour timeframe and joining mid-development, I took charge of organizing the game scene design through to implementation. After grasping the existing structure, I redefined specifications and reconstructed the logic, ultimately bringing it to a fully functional state.\n\n[Architecture Design]\nSeparated responsibilities for NPC generation, individual control, and random event management at the class level.\n\n- ScreenEdgeSpawner: NPC spawn management and probability control.\n- PersonController: Individual movement and state management.\n- RandomEventManager: Control of external events such as weather.\n\nSeparating generation from individual behavior created a structure resilient to spawn specification changes and event additions.\n\n[NPC Pathfinding Design]\nImplemented 3 types of route patterns (pass-through / heading to dense areas / guided to specific points).\nRoutes are assigned via probability at spawn, with units controlling their own behavioral branching.\nPrevented processing bloat by establishing states for each role.\n\n[State Interruption via External Events]\nImplemented logic to overwrite existing states when a rain event occurs.\nEstablished conditional branching to prevent state conflicts and avoid double execution. Designed a structure to safely switch states while maintaining animation synchronization.\n\n[Efficiency via Editor Extensions]\nImplemented CharacterCreatorEditor (Unity Editor extension).\nAutomated character generation and animation settings, reducing manual labor. Suppressed setup costs during short-term development.\n\n[Design Decisions]\nWorking backward from the development period, elements not directly tied to the core experience were shifted to phased implementation.\nPrioritized logic stability, focusing on the completeness of state management over experimental features.",
        imageUrls: [
            "/projects/GameJam/GlobalGameJam/GlobalGameJam1.png",
            "/projects/GameJam/GlobalGameJam/GlobalGameJam2.png",
            "/projects/GameJam/GlobalGameJam/GlobalGameJam3.png",
            "/projects/GameJam/GlobalGameJam/GlobalGameJam4.png",
        ],
        backgroundUrl: "/projects/GameJam/GlobalGameJam/GlobalGameJamBack.png",
        technologies: ["Unity", "C#"],
        githubUrl: "https://github.com/MKTkakumei/GGJ2026_01",
        downloadUrl: "https://drive.google.com/drive/folders/1zqc_DEku_vkQqIurhKQhbbz50RdoKSxb?usp=sharing",
    },
    {
        id: "gj-2",
        title: "Takahashi",
        description: "ゲームジャム高梁 参加作品\nプログラムリーダー・キャラクターのプログラミング担当\n\n36時間という短期間開発において、プログラムリーダーとして3名の実装分担を担当しました。プレイヤー制御とその他キャラクター制御の大枠のみを定義し、並列実装によるスピードを優先しましたが、初期段階での設計統一や実装方針の共有が不十分でした。その結果、挙動の不整合やレビュー不足が発生し、後半での修正コストが増大、最終的に一部機能未完成・バグ残存という課題を残しました。\n\n本経験から、短期開発ほど初期設計の明確化と技術レベル差を考慮したタスク設計、定期的な進捗レビューが重要であると学びました。",
        descriptionEn: "Game Jam Takahashi Participant\nProgram Leader & Character Programmer\n\nDuring a short 36-hour development period, I served as the programming leader managing tasks for 3 members. I prioritized speed through parallel implementation by defining only the broad outlines of player and character controls. However, early-stage design unification and sharing of implementation policies were insufficient. As a result, behavioral inconsistencies and a lack of reviews occurred, increasing revision costs in the latter half, ultimately leaving unresolved issues like incomplete features and lingering bugs.\n\nFrom this experience, I learned that in short-term development, clarifying initial designs, tailoring task allocation to varying technical skill levels, and conducting regular progress reviews are critically important.",
        imageUrls: [
            "/projects/GameJam/GameJamTakahashi/GameJamTakahashi1.png",
            "/projects/GameJam/GameJamTakahashi/GameJamTakahashi2.png",
            "/projects/GameJam/GameJamTakahashi/GameJamTakahashi3.png",
            "/projects/GameJam/GameJamTakahashi/GameJamTakahashi4.png",
        ],
        backgroundUrl: "/projects/GameJam/GameJamTakahashi/GameJamTakahashiBack.png",
        technologies: ["Unity", "C#"],
        githubUrl: "https://github.com/Hamster-jpg/mistshooter",
        downloadUrl: "https://drive.google.com/drive/folders/18Ln0c9baNiyWdGVi3LZ3yTVFrFlPXg9k?usp=sharing",
    },
    {
        id: "gj-3",
        title: "BitSummit",
        description: "BitSummit GameJam 参加作品\nスコア全般・リザルト画面全般",
        descriptionEn: "Game Jam entry",
        imageUrls: [
            "/projects/GameJam/BitSummitGameJam/BitSummitGameJam1.png",
            "/projects/GameJam/BitSummitGameJam/BitSummitGameJam2.png",
            "/projects/GameJam/BitSummitGameJam/BitSummitGameJam3.png",
            "/projects/GameJam/BitSummitGameJam/BitSummitGameJam4.png",
        ],
        backgroundUrl: "/projects/GameJam/BitSummitGameJam/BitSummitGameJamBack.jpg",
        technologies: ["Unity", "C#"],
        githubUrl: "https://github.com/hy0by0/Bug_Cord",
        downloadUrl: "https://drive.google.com/drive/folders/1mp87IbYL_i7KyUzruZjmDjG0Ns4ulh1v?usp=sharing",
    },
    {
        id: "gj-4",
        title: "Saikyou",
        description: "最強ゲームジャム 参加作品\nタイトル画面全般",
        descriptionEn: "Game Jam entry",
        imageUrls: [
            "/projects/GameJam/SaikyouGameJam/SaikyouGameJam1.png",
            "/projects/GameJam/SaikyouGameJam/SaikyouGameJam2.png",
            "/projects/GameJam/SaikyouGameJam/SaikyouGameJam3.png",
            "/projects/GameJam/SaikyouGameJam/SaikyouGameJam4.png",
        ],
        backgroundUrl: "/projects/GameJam/SaikyouGameJam/SaikyouGameJamBack.png",
        technologies: ["Unity", "C#"],
        githubUrl: "https://github.com/kayinazlost/ExcellentTeam",
        downloadUrl: "https://drive.google.com/drive/folders/1oc61BSOcm2yNSzKaiYQrBK2_w6dQYO-7?usp=sharing",
    },
    {
        id: "gj-5",
        title: "Shoutengai",
        description: "商店街ゲームジャム 参加作品\n左上のうんちバーの配置",
        descriptionEn: "Game Jam entry",
        imageUrls: [
            "/projects/GameJam/ShoutengaiGameJam/ShoutengaiGameJam1.png",
            "/projects/GameJam/ShoutengaiGameJam/ShoutengaiGameJam2.png",
            "/projects/GameJam/ShoutengaiGameJam/ShoutengaiGameJam3.png",
            "/projects/GameJam/ShoutengaiGameJam/ShoutengaiGameJam4.png",
        ],
        backgroundUrl: "/projects/GameJam/ShoutengaiGameJam/ShoutengaiGameJamBack.png",
        technologies: ["Unity", "C#"],
        githubUrl: "https://github.com/SanukiGameN108/ShotengaiGJ2024_TeamD",
        downloadUrl: "https://drive.google.com/drive/folders/1JMCisiSB07Oe4FoF3CWBAfveRvkJsGrf?usp=sharing",
    },
];
