export const m_ProjectData = [
    {
        id: 1,
        title: "Axis:Save",
        description: "『視覚演出』をコンセプトとして制作した作品です。\n\n▸ チュートリアルシーンを作らず、プレイ中に<strong>UIテキストで説明を進める</strong>ことで没入感・ゲームテンポを重視\n▸ 刀を抜く瞬間のズームでプレイヤーの視点を一点に集中させ、<strong>視界的な溜め</strong>として期待感を高める演出\n▸ ダッチチルト（水平を崩す）で次の瞬間に起こるスピード感を視覚的に表現\n▸ マップの提供以外は<strong>すべて自作</strong>\n\n<strong>制作期間</strong> : 3ヶ月 &emsp; <strong>チーム人数</strong> : 個人制作 &emsp; <strong>プラットフォーム</strong> : PC / Windows",
        descriptionEn: "A game created with the concept of <strong>'visual direction'</strong>.\n\n▸ No tutorial scene — <strong>instructions are delivered via UI text during gameplay</strong>, prioritizing immersion and pacing\n▸ Zooming in at the moment of drawing the sword focuses the player's eye on a single point, functioning as a <strong>visual pause</strong> that builds anticipation\n▸ Dutch tilt (breaking the horizon) visually expresses the sense of speed in the next moment\n▸ <strong>Everything is self-made</strong> except for the map assets\n\n<strong>Duration</strong> : 3 months &emsp; <strong>Team</strong> : Solo &emsp; <strong>Platform</strong> : PC / Windows",
        videoUrl: "/projects/AxisSave/Game4.mp4",
        imageUrls: [
            "/projects/AxisSave/AxisSave1.png",
            "/projects/AxisSave/AxisSave2.png",
            "/projects/AxisSave/AxisSave3.png",
            "/projects/AxisSave/AxisSave4.png",
        ],
        githubUrl: "https://github.com/chogeru/3DCombat",
        downloadUrl: "https://drive.google.com/drive/folders/1vabvlXhPTLtVtxnlnO1IsJV7u5S8FY4F?usp=drive_link",
        backgroundUrl: "/projects/AxisSave/AxisSaveBack.png",
        technologies: ["Unity", "C#", "HLSL"],
    },
    {
        id: 2,
        title: "PlanetariumVR",
        description: "UniTaskと体験設計を学習目的とした作品です。\n\n▸ コンセプト：『自然に体が動いて体験に入れる』設計\n▸ 音声の発生地点を星座に設定 → 視線誘導を自然に促す\n▸ 音声再生完了をUniTaskで待ってから星座をフェードイン → 体験シーケンスの構築\n\n<strong>制作期間</strong> : 2日 &emsp; <strong>チーム人数</strong> : 個人制作 &emsp; <strong>プラットフォーム</strong> : VR",
        descriptionEn: "A project focused on learning UniTask and experience design.\n\n▸ Concept: A design where <strong>the body naturally moves into the experience</strong>\n▸ Sound sources placed at constellations → naturally guides the user's gaze\n▸ Wait for audio playback to complete via UniTask, then fade in the constellation → building an experience sequence\n\n<strong>Duration</strong> : 2 days &emsp; <strong>Team</strong> : Solo &emsp; <strong>Platform</strong> : VR",
        videoUrl: "",
        imageUrls: [
            "/projects/PlanetariumVR/PlanetariumVR1.png",
            "/projects/PlanetariumVR/Planetarium2.png",
        ],
        githubUrl: "https://github.com/sogotoya/Planetarium_VR",
        downloadUrl: "",
        backgroundUrl: "/projects/PlanetariumVR/PlanetariumVRBack.png",
        technologies: ["Unity", "C#", "VR"],
    },
    {
        id: 3,
        title: "DartsVR",
        description: "VRダーツゲーム",
        descriptionEn: "A VR darts game",
        videoUrl: "",
        imageUrls: [
            "/projects/DartsVR/DartsVR1.png",
            "/projects/DartsVR/DartsVR2.png",
        ],
        githubUrl: "https://github.com/sogotoya/DartsVR",
        downloadUrl: "",
        backgroundUrl: "/projects/DartsVR/DartsVRBack.png",
        technologies: ["Unity", "C#", "VR"],
    },
    {
        id: 4,
        title: "Orimichikun",
        description: "2D横スクロールアクションゲーム",
        descriptionEn: "2D Side-scrolling Action Game",
        videoUrl: "",
        imageUrls: [
            "/projects/Orimichikun/Orimichikun2.png",
            "/projects/Orimichikun/Orimichikun3.png",
            "/projects/Orimichikun/Orimichikun4.png",
            "/projects/Orimichikun/Orimichikun5.png",
            "/projects/Orimichikun/Orimichikun1.png",
        ],
        githubUrl: "https://github.com/sogotoya/Orimichikun",
        downloadUrl: "",
        backgroundUrl: "/projects/Orimichikun/OrimichikunBack.png",
        technologies: ["Unity", "C#"],
    },
];

// ツール一覧
export const m_ToolData = [];

// ゲームジャム作品
export const m_GameJamData = [
    {
        id: "gj-1",
        title: "Global",
        description: "Global Game Jam 参加作品",
        descriptionEn: "Global Game Jam entry",
        imageUrls: [
            "/projects/GameJam/GlobalGameJam/GlobalGameJam1.png",
            "/projects/GameJam/GlobalGameJam/GlobalGameJam2.png",
            "/projects/GameJam/GlobalGameJam/GlobalGameJam3.png",
            "/projects/GameJam/GlobalGameJam/GlobalGameJam4.png",
        ],
        backgroundUrl: "/projects/GameJam/GlobalGameJam/GlobalGameJamBack.png",
        technologies: ["Unity", "C#"],
    },
    {
        id: "gj-2",
        title: "Takahashi",
        description: "ゲームジャム参加作品",
        descriptionEn: "Game Jam entry",
        imageUrls: [
            "/projects/GameJam/GameJamTakahashi/GameJamTakahashi1.png",
            "/projects/GameJam/GameJamTakahashi/GameJamTakahashi2.png",
            "/projects/GameJam/GameJamTakahashi/GameJamTakahashi3.png",
            "/projects/GameJam/GameJamTakahashi/GameJamTakahashi4.png",
        ],
        backgroundUrl: "/projects/GameJam/GameJamTakahashi/GameJamTakahashiBack.png",
        technologies: ["Unity", "C#"],
    },
    {
        id: "gj-3",
        title: "BitSummit",
        description: "ゲームジャム参加作品",
        descriptionEn: "Game Jam entry",
        imageUrls: [],
        technologies: ["Unity", "C#"],
    },
    {
        id: "gj-4",
        title: "Saikyou",
        description: "ゲームジャム参加作品",
        descriptionEn: "Game Jam entry",
        imageUrls: [],
        technologies: ["Unity", "C#"],
    },
    {
        id: "gj-5",
        title: "Shoyutengai",
        description: "ゲームジャム参加作品",
        descriptionEn: "Game Jam entry",
        imageUrls: [],
        technologies: ["Unity", "C#"],
    },
];
